# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

name: Other issue
description: Generic issue template

body:
  
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I confirm this is **not a question, or helpers feature request**. *Otherwise, use the Discussions page.*
          required: true
        - label: I confirm this is **not an issue encountered with an installed build of pypdfium2, but about some other aspect of the project** (specify below). *Otherwise, use one of the package templates (PyPA/conda), even if you believe this is not a package-specific issue. (This is e.g. required for debugging info.)*
          required: true
        - label: I confirm this is **not about an unofficial build of pypdfium2**, or an effort to create a such. *We do not support third-party builds, and they are not eligible for a bug report. Please use our official packages instead.*
          required: true
  
  - type: input
    attributes:
      label: Reason for Generic issue (keyword/topic)
      description: Briefly **justify** why you are using the Generic issue form.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem.
    validations:
      required: true
