name: Publish Packages to Staging
on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  publish_package:
    uses: Ganymede-Bio/common-gh-workflows/.github/workflows/publish-python-package.yaml@main
    with:
      GCP_PROJECT: ganymede-core-staging
      WORKLOAD_IDENTITY_PROVIDER: projects/980665281034/locations/global/workloadIdentityPools/ganymede-core-staging-pool/providers/ganymede-core-staging-provider
      WORKLOAD_IDENTITY_SERVICE_ACCOUNT: py-upload