name: Publish Packages
on:
  push:
    branches:
      - 'main'
permissions:
  contents: 'read'
  id-token: 'write'
  
jobs:
  publish_package:
    uses: Ganymede-Bio/common-gh-workflows/.github/workflows/publish-python-package.yaml@publish-python-package
    with:
      GCP_PROJECT: ganymede-core-dev
      WORKLOAD_IDENTITY_PROVIDER: projects/248644630671/locations/global/workloadIdentityPools/ganymede-core-dev-pool/providers/ganymede-core-dev-provider
      WORKLOAD_IDENTITY_SERVICE_ACCOUNT: py-upload